name = "your-worker-name"  # Your Cloudflare Worker name
type = "javascript"        # Language your Worker is written in, here it's JavaScript
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"  # Your Cloudflare Account ID
workers_dev = true         # Set to false if using a custom domain
route = "https://*.eowsubluf.cfd/*"  # Your Cloudflare Worker route or custom domain
zone_id = "4d9495e481e17d4f7e1b6778f02cbdf8"  # Your Cloudflare Zone ID

[env.production]
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"
workers_dev = true         # Change to false for custom domain
compatibility_date = "2025-03-17"
