name = "your-worker-name"
type = "javascript"

account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"
workers_dev = true  # Change to false if using a custom domain
route = "https://*.eowsubluf.cfd/*"
zone_id = "4d9495e481e17d4f7e1b6778f02cbdf8"

[env.production]
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"
workers_dev = true
compatibility_date = "2025-03-17"
