name = "your-worker-name"  # Replace with your actual worker name
main = "src/worker.js"  # Specify the main file for your worker (adjust as necessary)
workers_dev = true  # Set to false if using a custom domain
route = "https://*.eowsubluf.cfd/*"  # Your Cloudflare Worker route or custom domain

[env.production]
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"  # Your Cloudflare Account ID
workers_dev = true  # Set to false if using a custom domain
compatibility_date = "2025-03-17"  # The compatibility date for your worker
