name = "your-worker-name"
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"
workers_dev = true
route = "https://*.eowsubluf.cfd/*"
compatibility_date = "2025-03-10"

# Specify the correct path to the worker script in the src folder
main = "src/worker.js"
