name = "your-worker-name"
type = "javascript"

account_id = "your-account-id"
workers_dev = true
compatibility_date = "2025-03-17"

[env.production]
zone_id = "your-zone-id"
route = "your-cloudflare-worker-route"
