name = "redirect-worker"
account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2025-03-17"
main = "src/worker.js"  # Specify the correct path to the worker script

# Uncomment and set if deploying to a specific route
# route = "yourdomain.com/*"
# zone_id = "your-cloudflare-zone-id"
