name = "your-worker-name"
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"
workers_dev = true
route = "https://*.eowsubluf.cfd/*"
compatibility_date = "2025-03-10"

main = "src/worker.js"  # Make sure this path is correct
