name = "your-worker-name"  # Replace with your actual Cloudflare Worker name
type = "javascript"  # Ensure this is set correctly

# Cloudflare Account and Zone IDs
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"  # Your Cloudflare Account ID
workers_dev = true  # Set to false if using a custom domain
route = "https://*.eowsubluf.cfd/*"  # Your Cloudflare Worker route or custom domain
zone_id = "4d9495e481e17d4f7e1b6778f02cbdf8"  # Your Cloudflare Zone ID

[env.production]
account_id = "cc52209c791ecf1ea0434bd5e3ddbbda"  # Ensure this is your account ID for production
workers_dev = true  # Set to false for production environment if using a custom domain
compatibility_date = "2025-03-17"  # Update to the current date
