name: Deploy to Cloudflare Workers

on:
  push:
    branches:
<<<<<<< HEAD
      - main  # Change to your active branch if needed
=======
      - main
>>>>>>> 6124bc8 (Initial commit)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
<<<<<<< HEAD
        uses: actions/checkout@v3
=======
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
>>>>>>> 6124bc8 (Initial commit)

      - name: Install dependencies
        run: npm install

      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy
        env:
<<<<<<< HEAD
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
=======
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}  # Cloudflare API token
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}  # Should match cc52209c791ecf1ea0434bd5e3ddbbda
>>>>>>> 6124bc8 (Initial commit)
