name: Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloudflare Wrangler
        run: npm install -g wrangler

      - name: Configure Wrangler with Cloudflare API Key
        run: echo ${{ secrets.CLOUDFLARE_API_KEY }} > ~/.wrangler/config.toml

      - name: Deploy to Cloudflare Worker
        run: |
          wrangler login --api-key ${{ secrets.CLOUDFLARE_API_KEY }}
          wrangler publish --env production
